name: Yuguang XIAO
description: Homepage of Yuguang XIAO
url: "https://yuguangxiao.github.io"
baseurl: ""

author:
  avatar           : "yuguang.png"
  name             : "Yuguang XIAO (肖煜光)"
  pronouns         : ""
  bio              : "A M2 student in Probability and Random models"
  location         : "Paris, France"
  employer         : "LPSM, Sorbonne University"
  uri              : "https://xiaoyuguang.fr"
  email            : "yuguang.xiao.maths@gmail.com"
  academia         : ""
  arxiv            : ""
  googlescholar    : ""
  inspire-hep      : ""
  impactstory      : ""
  orcid            : ""
  semantic         : ""
  pubmed           : ""
  researchgate     : ""
  scopus           : ""
  bitbucket        : ""
  codepen          : ""
  dribbble         : ""
  github           : "Lucien-XIAO"
  kaggle           : ""
  stackoverflow    : ""
  artstation       : ""
  bluesky          : ""
  facebook         : ""
  flickr           : ""
  foursquare       : ""
  goodreads        : ""
  google_plus      : ""
  keybase          : ""
  instagram        : ""
  lastfm           : ""
  linkedin         : "your-linkedin-id"
  mastodon         : ""
  medium           : ""
  pinterest        : ""
  soundcloud       : ""
  steam            : ""
  telegram         : ""
  tumblr           : ""
  twitter          : ""
  vine             : ""
  weibo            : ""
  wikipedia        : ""
  xing             : ""
  youtube          : ""
  zhihu            : ""
